listen_addresses = '*'
max_connections = 100
shared_buffers = 256MB
effective_cache_size = 768MB
log_destination = 'stderr'
logging_collector = off
log_statement = 'mod'
log_min_duration_statement = 250ms
log_connections = off
log_disconnections = off
shared_preload_libraries = ''

# Most settings in this file are reloadable:
# docker compose exec postgres pg_ctl reload -D /var/lib/postgresql/data
