root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/bankapi ./cmd/api"
entrypoint = "./tmp/bankapi"
delay = 1000
exclude_dir = ["tmp", "vendor", ".git"]
include_ext = ["go", "sql", "toml"]
stop_on_error = true

[log]
time = true

[misc]
clean_on_exit = true
